export const HOSPITALS = [
  { name: "Rajiv Gandhi Government General Hospital", lat: 13.0824, lon: 80.2785, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Dermatologist", "Oncologist"], avgWaitMin: 62 },
  { name: "Stanley Medical College Hospital", lat: 13.1057, lon: 80.2923, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Dermatologist", "Oncologist"], avgWaitMin: 74 },
  { name: "Kilpauk Medical College Hospital", lat: 13.0873, lon: 80.242, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Dermatologist"], avgWaitMin: 79 },
  { name: "Institute of Child Health, Egmore", lat: 13.0761, lon: 80.2624, departments: ["Pediatrician", "General Physician", "Neurologist"], avgWaitMin: 63 },
  { name: "Government Ophthalmic Hospital", lat: 13.08, lon: 80.279, departments: ["General Physician", "Dermatologist"], avgWaitMin: 74 },
  { name: "Apollo Hospitals, Greams Road", lat: 13.0618, lon: 80.2615, departments: ["Cardiologist", "Neurologist", "Orthopedician", "Oncologist", "General Physician", "Gynecologist", "Pediatrician", "Dermatologist"], avgWaitMin: 48 },
  { name: "MGM Healthcare, Nelson Manickam Road", lat: 13.062, lon: 80.2579, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist"], avgWaitMin: 45 },
  { name: "Kauvery Hospital, Alwarpet", lat: 13.0339, lon: 80.2549, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Gynecologist", "Oncologist"], avgWaitMin: 64 },
  { name: "Dr. Rela Institute and Medical Centre", lat: 13.0011, lon: 80.2182, departments: ["General Physician", "Cardiologist", "Neurologist", "Oncologist", "Orthopedician", "Gynecologist"], avgWaitMin: 53 },
  { name: "Billroth Hospitals, Shenoy Nagar", lat: 13.0874, lon: 80.2179, departments: ["General Physician", "Gynecologist", "Cardiologist", "Neurologist", "Orthopedician"], avgWaitMin: 27 },
  { name: "Dr. Mehta's Hospitals, Chetpet", lat: 13.0726, lon: 80.2413, departments: ["Orthopedician", "General Physician", "Cardiologist", "Neurologist"], avgWaitMin: 30 },
  { name: "Madras Medical Mission", lat: 13.069, lon: 80.1949, departments: ["Cardiologist", "Neurologist", "General Physician", "Orthopedician"], avgWaitMin: 54 },
  { name: "Prashanth Hospitals, Velachery", lat: 12.9731, lon: 80.2163, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician"], avgWaitMin: 32 },
  { name: "Gleneagles Global Health City, Perumbakkam", lat: 12.9191, lon: 80.2185, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist"], avgWaitMin: 48 },
  { name: "Sundaram Medical Foundation, Adyar", lat: 13.0012, lon: 80.2571, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist"], avgWaitMin: 43 },
  { name: "Voluntary Health Services, Taramani", lat: 12.9827, lon: 80.2183, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Dermatologist"], avgWaitMin: 32 },
  { name: "SIMS Hospital, Vadapalani", lat: 13.0521, lon: 80.2142, departments: ["Cardiologist", "General Physician", "Neurologist", "Orthopedician", "Oncologist", "Gynecologist"], avgWaitMin: 54 },
  { name: "SRM Institutes for Medical Science, Vadapalani", lat: 13.0515, lon: 80.2246, departments: ["Orthopedician", "Neurologist", "Gynecologist", "Pediatrician", "General Physician"], avgWaitMin: 36 },
  { name: "Vijaya Hospital, Vadapalani", lat: 13.0514, lon: 80.2117, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist"], avgWaitMin: 30 },
  { name: "Fortis Malar Hospital, Adyar", lat: 13.0062, lon: 80.2553, departments: ["Cardiologist", "Neurologist", "Orthopedician", "Oncologist", "General Physician", "Gynecologist"], avgWaitMin: 62 },
  { name: "MIOT International Hospital, Manapakkam", lat: 12.9921, lon: 80.1788, departments: ["Orthopedician", "Cardiologist", "Neurologist", "General Physician", "Oncologist", "Gynecologist"], avgWaitMin: 52 },
  { name: "Sri Ramachandra Medical Centre, Porur", lat: 13.0343, lon: 80.1646, departments: ["Cardiologist", "Neurologist", "General Physician", "Oncologist", "Gynecologist", "Pediatrician", "Dermatologist", "Orthopedician"], avgWaitMin: 57 },
  { name: "Madha Medical College Hospital, Kovur", lat: 13.0524, lon: 80.1202, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist"], avgWaitMin: 29 },
  { name: "Saveetha Medical College Hospital, Poonamallee", lat: 13.0278, lon: 80.0182, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Gynecologist", "Pediatrician", "Dermatologist"], avgWaitMin: 49 },
  { name: "Mangalam Hospital, Poonamallee", lat: 13.049, lon: 80.0945, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 40 },
  { name: "ACS Medical Centre, Poonamallee", lat: 13.0481, lon: 80.124, departments: ["General Physician", "Gynecologist", "Pediatrician"], avgWaitMin: 29 },
  { name: "Sriranga Hospital, Poonamallee", lat: 13.0455, lon: 80.093, departments: ["General Physician", "Pediatrician"], avgWaitMin: 15 },
  { name: "Poonamallee Government Hospital", lat: 13.0473, lon: 80.09, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 74 },
  { name: "Sriram Hospital, Tambaram", lat: 12.9249, lon: 80.0951, departments: ["General Physician", "Gynecologist", "Orthopedician", "Pediatrician"], avgWaitMin: 36 },
  { name: "Tambaram Government Hospital", lat: 12.923, lon: 80.1, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist"], avgWaitMin: 66 },
  { name: "Chromepet General Hospital", lat: 12.9516, lon: 80.1448, departments: ["General Physician", "Orthopedician", "Gynecologist"], avgWaitMin: 42 },
  { name: "Kauvery Medical Centre, Trichy Road", lat: 13.0218, lon: 80.2105, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist"], avgWaitMin: 33 },
  { name: "Ambulatory Care Centre, Kilpauk", lat: 13.0864, lon: 80.2405, departments: ["General Physician", "Pediatrician", "Dermatologist"], avgWaitMin: 30 },
  { name: "Sathya Hospital, Anna Nagar", lat: 13.0879, lon: 80.2087, departments: ["General Physician", "Gynecologist", "Orthopedician", "Cardiologist"], avgWaitMin: 30 },
  { name: "Karpagam Hospital, Porur", lat: 13.0377, lon: 80.1571, departments: ["General Physician", "Gynecologist", "Pediatrician"], avgWaitMin: 29 },
  { name: "Narayana Health, Perumbakkam", lat: 12.9204, lon: 80.2153, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Pediatrician"], avgWaitMin: 58 },
  { name: "Frontier Lifeline Hospital, R K Nagar", lat: 13.0818, lon: 80.2363, departments: ["Cardiologist", "Neurologist", "General Physician", "Pediatrician", "Gynecologist"], avgWaitMin: 60 },
  { name: "Shankar Nethralaya, College Road", lat: 13.0671, lon: 80.258, departments: ["General Physician", "Dermatologist", "Neurologist"], avgWaitMin: 39 },
  { name: "Sri Sakthi Hospital, Ambattur", lat: 13.0968, lon: 80.1564, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 27 },
  { name: "Surya Hospital, Perambur", lat: 13.1091, lon: 80.2464, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist"], avgWaitMin: 31 },
  { name: "Vadamalapuram General Clinic, Avadi", lat: 13.1148, lon: 80.0962, departments: ["General Physician", "Pediatrician"], avgWaitMin: 16 },
  { name: "Apollo Reach Hospital, Sholinganallur", lat: 12.8992, lon: 80.2279, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist", "Pediatrician"], avgWaitMin: 34 },
  { name: "SRM Medical College Hospital, Kattankulathur", lat: 12.8231, lon: 80.0444, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Oncologist", "Dermatologist"], avgWaitMin: 52 },
  { name: "Chettinad Super Speciality Hospital, Kelambakkam", lat: 12.8353, lon: 80.2278, departments: ["Cardiologist", "Neurologist", "General Physician", "Orthopedician", "Oncologist", "Gynecologist"], avgWaitMin: 48 },
  { name: "Vels Medical Centre, Pallavaram", lat: 12.9673, lon: 80.1511, departments: ["General Physician", "Gynecologist", "Pediatrician"], avgWaitMin: 36 },
  { name: "PSG Hospitals, Coimbatore", lat: 11.024, lon: 77.0001, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist", "Pediatrician", "Dermatologist"], avgWaitMin: 47 },
  { name: "Kovai Medical Centre (KMCH)", lat: 11.0063, lon: 77.0001, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist"], avgWaitMin: 55 },
  { name: "G.Kuppuswamy Naidu Memorial Hospital", lat: 11.0031, lon: 76.9765, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician"], avgWaitMin: 27 },
  { name: "Apollo Speciality Hospital, Coimbatore", lat: 11.001, lon: 76.9741, departments: ["Cardiologist", "Neurologist", "Orthopedician", "Oncologist", "General Physician", "Gynecologist"], avgWaitMin: 52 },
  { name: "Coimbatore Medical College Hospital", lat: 11.0168, lon: 76.9558, departments: ["General Physician", "Gynecologist", "Pediatrician", "Dermatologist", "Cardiologist", "Neurologist", "Orthopedician", "Oncologist"], avgWaitMin: 67 },
  { name: "Sri Ramakrishna Hospital, Coimbatore", lat: 11.0218, lon: 76.9786, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Gynecologist", "Oncologist", "Pediatrician"], avgWaitMin: 49 },
  { name: "Meenakshi Mission Hospital, Coimbatore", lat: 11.0148, lon: 77.004, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 25 },
  { name: "RVS Hospital, RS Puram", lat: 11.0215, lon: 77.0082, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist"], avgWaitMin: 34 },
  { name: "Lotus Eye Hospital, Coimbatore", lat: 11.0231, lon: 77.0041, departments: ["General Physician", "Dermatologist"], avgWaitMin: 26 },
  { name: "KG Hospital, Coimbatore", lat: 11.0042, lon: 76.9659, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Orthopedician"], avgWaitMin: 44 },
  { name: "Tiruppur Government Hospital", lat: 11.1054, lon: 77.3329, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Dermatologist"], avgWaitMin: 76 },
  { name: "KM Hospital, Tiruppur", lat: 11.1085, lon: 77.3411, departments: ["General Physician", "Gynecologist", "Orthopedician", "Pediatrician", "Cardiologist"], avgWaitMin: 36 },
  { name: "Arun Hospital, Tiruppur", lat: 11.1063, lon: 77.348, departments: ["General Physician", "Gynecologist", "Pediatrician"], avgWaitMin: 30 },
  { name: "Erode Government Hospital", lat: 11.339, lon: 77.7268, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Dermatologist"], avgWaitMin: 76 },
  { name: "KG Hospital, Erode", lat: 11.341, lon: 77.7172, departments: ["General Physician", "Gynecologist", "Orthopedician", "Cardiologist", "Pediatrician"], avgWaitMin: 30 },
  { name: "Manibaratham Hospital, Erode", lat: 11.3425, lon: 77.721, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 25 },
  { name: "Government Rajaji Hospital, Madurai", lat: 9.9195, lon: 78.1224, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Dermatologist", "Oncologist"], avgWaitMin: 77 },
  { name: "Meenakshi Mission Hospital, Madurai", lat: 9.9252, lon: 78.1198, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist", "Pediatrician"], avgWaitMin: 63 },
  { name: "Apollo Hospitals, Madurai", lat: 9.9252, lon: 78.1248, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist"], avgWaitMin: 46 },
  { name: "Velammal Medical College, Madurai", lat: 9.8826, lon: 78.0744, departments: ["General Physician", "Gynecologist", "Orthopedician", "Neurologist", "Cardiologist", "Pediatrician"], avgWaitMin: 53 },
  { name: "Kamakshi Hospital, Madurai", lat: 9.9155, lon: 78.1273, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 25 },
  { name: "ARV Hospital, Madurai", lat: 9.9214, lon: 78.1165, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist"], avgWaitMin: 29 },
  { name: "Devaki Hospital, Madurai", lat: 9.918, lon: 78.13, departments: ["General Physician", "Gynecologist", "Pediatrician"], avgWaitMin: 32 },
  { name: "Sri Sowdambika Hospital, Madurai", lat: 9.924, lon: 78.121, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 36 },
  { name: "Aravind Eye Hospital, Madurai", lat: 9.9195, lon: 78.1262, departments: ["General Physician", "Dermatologist", "Neurologist"], avgWaitMin: 28 },
  { name: "Thirumalai Mission Hospital, Ranipet", lat: 12.9303, lon: 79.3323, departments: ["General Physician", "Gynecologist", "Orthopedician", "Cardiologist"], avgWaitMin: 42 },
  { name: "Apollo Speciality Hospital, Trichy", lat: 10.7905, lon: 78.7047, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist"], avgWaitMin: 50 },
  { name: "Kauvery Hospital, Trichy", lat: 10.7857, lon: 78.687, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist", "Pediatrician"], avgWaitMin: 59 },
  { name: "Mahatma Gandhi Memorial Government Hospital, Trichy", lat: 10.805, lon: 78.6934, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Dermatologist", "Oncologist"], avgWaitMin: 74 },
  { name: "SRM Trichy Hospital", lat: 10.7601, lon: 78.702, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist"], avgWaitMin: 34 },
  { name: "Ponni Hospital, Trichy", lat: 10.7988, lon: 78.6919, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 32 },
  { name: "Sankara Hospital, Trichy", lat: 10.8012, lon: 78.68, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician"], avgWaitMin: 41 },
  { name: "Royal Care Super Speciality, Trichy", lat: 10.79, lon: 78.7119, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist"], avgWaitMin: 56 },
  { name: "Thanjavur Medical College Hospital", lat: 10.7903, lon: 79.1294, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Oncologist", "Dermatologist"], avgWaitMin: 65 },
  { name: "PRIST Hospital, Thanjavur", lat: 10.787, lon: 79.1378, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 38 },
  { name: "Kumbakonam Government Hospital", lat: 10.9602, lon: 79.3845, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist"], avgWaitMin: 71 },
  { name: "Salem Government Medical College Hospital", lat: 11.6545, lon: 78.1556, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Dermatologist", "Oncologist"], avgWaitMin: 69 },
  { name: "Vinayaka Mission's Medical College, Salem", lat: 11.6643, lon: 78.146, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist", "Neurologist"], avgWaitMin: 53 },
  { name: "Shanmuga Hospital, Salem", lat: 11.6542, lon: 78.1631, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist"], avgWaitMin: 27 },
  { name: "Sakthi Hospital, Salem", lat: 11.6621, lon: 78.1704, departments: ["General Physician", "Gynecologist", "Pediatrician"], avgWaitMin: 39 },
  { name: "Sugam Hospital, Salem", lat: 11.6572, lon: 78.159, departments: ["General Physician", "Orthopedician", "Gynecologist", "Cardiologist"], avgWaitMin: 36 },
  { name: "Dhanalakshmi Hospitals, Salem", lat: 11.652, lon: 78.156, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 43 },
  { name: "SRIHER Medical College, Salem", lat: 11.6689, lon: 78.1431, departments: ["General Physician", "Cardiologist", "Orthopedician", "Neurologist"], avgWaitMin: 30 },
  { name: "Namakkal Government Hospital", lat: 11.2213, lon: 78.1674, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 61 },
  { name: "Dharmapuri Government Hospital", lat: 12.1211, lon: 78.1582, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Orthopedician"], avgWaitMin: 78 },
  { name: "Krishnagiri Government Hospital", lat: 12.5266, lon: 78.2138, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 68 },
  { name: "Government Tirunelveli Medical College Hospital", lat: 8.7284, lon: 77.7003, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Dermatologist", "Oncologist"], avgWaitMin: 62 },
  { name: "TISL Hospitals, Tirunelveli", lat: 8.7139, lon: 77.7567, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Gynecologist"], avgWaitMin: 51 },
  { name: "Nirmala Hospital, Tirunelveli", lat: 8.7162, lon: 77.7384, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 28 },
  { name: "Narayana Hospital, Tirunelveli", lat: 8.721, lon: 77.75, departments: ["General Physician", "Cardiologist", "Gynecologist", "Pediatrician"], avgWaitMin: 31 },
  { name: "Thoothukudi Medical College Hospital", lat: 8.8003, lon: 78.153, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Oncologist"], avgWaitMin: 74 },
  { name: "Ragunath Hospital, Thoothukudi", lat: 8.7642, lon: 78.1348, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 31 },
  { name: "Government Medical College, Nagercoil", lat: 8.1833, lon: 77.4119, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist", "Pediatrician", "Neurologist", "Dermatologist"], avgWaitMin: 63 },
  { name: "Karpaga Vinayaga Hospital, Nagercoil", lat: 8.1792, lon: 77.423, departments: ["General Physician", "Gynecologist", "Orthopedician"], avgWaitMin: 28 },
  { name: "Amala Hospital, Nagercoil", lat: 8.185, lon: 77.418, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 41 },
  { name: "Tenkasi Government Hospital", lat: 8.9601, lon: 77.3152, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 60 },
  { name: "Sivakasi Government Hospital", lat: 9.4533, lon: 77.7989, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist"], avgWaitMin: 68 },
  { name: "Virudhunagar Government Hospital", lat: 9.5847, lon: 77.9637, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 65 },
  { name: "Ramanathapuram Government Hospital", lat: 9.3712, lon: 78.8305, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Orthopedician"], avgWaitMin: 79 },
  { name: "Christian Medical College CMC, Vellore", lat: 12.9239, lon: 79.1326, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist", "Pediatrician", "Dermatologist"], avgWaitMin: 56 },
  { name: "Government Medical College Hospital, Vellore", lat: 12.9153, lon: 79.1342, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Oncologist"], avgWaitMin: 64 },
  { name: "Sri Narayani Hospital, Vellore", lat: 12.9083, lon: 79.0755, departments: ["General Physician", "Gynecologist", "Orthopedician", "Cardiologist"], avgWaitMin: 31 },
  { name: "Aravind Eye Hospital, Vellore", lat: 12.918, lon: 79.122, departments: ["General Physician", "Dermatologist", "Neurologist"], avgWaitMin: 30 },
  { name: "Thirumalai Mission Hospital, Vellore", lat: 12.9299, lon: 79.138, departments: ["General Physician", "Gynecologist", "Orthopedician", "Cardiologist", "Pediatrician"], avgWaitMin: 28 },
  { name: "Kancheepuram Government Hospital", lat: 12.8342, lon: 79.7036, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist", "Pediatrician", "Neurologist"], avgWaitMin: 77 },
  { name: "Sri Venkateshwara Hospital, Kancheepuram", lat: 12.8226, lon: 79.6987, departments: ["General Physician", "Gynecologist", "Orthopedician"], avgWaitMin: 43 },
  { name: "Ranipet Government Hospital", lat: 12.9313, lon: 79.3329, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 64 },
  { name: "Vandiyur Government Hospital, Tiruvannamalai", lat: 12.2253, lon: 79.0747, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Orthopedician"], avgWaitMin: 75 },
  { name: "Chidambaram Government Hospital", lat: 11.3993, lon: 79.6915, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 78 },
  { name: "Cuddalore Government Medical College Hospital", lat: 11.7447, lon: 79.768, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist", "Pediatrician", "Neurologist"], avgWaitMin: 66 },
  { name: "Villupuram Government Hospital", lat: 11.9394, lon: 79.4918, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Orthopedician"], avgWaitMin: 74 },
  { name: "JIPMER, Puducherry", lat: 11.9388, lon: 79.8293, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist", "Gynecologist", "Pediatrician", "Dermatologist"], avgWaitMin: 63 },
  { name: "Mahatma Gandhi Medical College, Puducherry", lat: 11.9591, lon: 79.828, departments: ["General Physician", "Cardiologist", "Neurologist", "Orthopedician", "Gynecologist", "Pediatrician", "Oncologist"], avgWaitMin: 54 },
  { name: "Governement Medical College, Puducherry", lat: 11.9401, lon: 79.8325, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Orthopedician"], avgWaitMin: 75 },
  { name: "Aravind Eye Hospital, Puducherry", lat: 11.9368, lon: 79.8298, departments: ["General Physician", "Dermatologist", "Neurologist"], avgWaitMin: 28 },
  { name: "Apollo BGS Hospital, Hosur", lat: 12.7409, lon: 77.8253, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist", "Pediatrician"], avgWaitMin: 25 },
  { name: "Hosur Government Hospital", lat: 12.7396, lon: 77.8271, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist"], avgWaitMin: 70 },
  { name: "Krishnagiri Government Hospital", lat: 12.5266, lon: 78.2138, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 68 },
  { name: "Government Medical College, Dindigul", lat: 10.3624, lon: 77.9695, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist", "Pediatrician", "Neurologist"], avgWaitMin: 63 },
  { name: "Annai Hospital, Dindigul", lat: 10.3665, lon: 77.972, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 32 },
  { name: "Theni Government Hospital", lat: 10.0104, lon: 77.4772, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Orthopedician"], avgWaitMin: 65 },
  { name: "Karur Government Hospital", lat: 10.9601, lon: 78.0765, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist", "Pediatrician"], avgWaitMin: 78 },
  { name: "Perambalur Government Hospital", lat: 11.2314, lon: 78.8803, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 76 },
  { name: "Ariyalur Government Hospital", lat: 11.1427, lon: 79.0782, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist"], avgWaitMin: 62 },
  { name: "Ooty Government Hospital", lat: 11.4102, lon: 76.695, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 68 },
  { name: "Gudalur Government Hospital", lat: 11.4988, lon: 76.4949, departments: ["General Physician", "Pediatrician", "Gynecologist"], avgWaitMin: 65 },
  { name: "Kodaikanal Government Hospital", lat: 10.2381, lon: 77.4892, departments: ["General Physician", "Pediatrician", "Gynecologist", "Orthopedician"], avgWaitMin: 68 },
  { name: "Sivaganga Government Hospital", lat: 9.8436, lon: 78.4767, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist"], avgWaitMin: 74 },
  { name: "Pudukkottai Government Hospital", lat: 10.3799, lon: 78.8211, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 74 },
  { name: "Nagapattinam Government Medical College", lat: 10.7672, lon: 79.8449, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Orthopedician", "Neurologist"], avgWaitMin: 60 },
  { name: "Mayiladuthurai Government Hospital", lat: 11.1016, lon: 79.6518, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 76 },
  { name: "Karaikal Government Hospital", lat: 10.9254, lon: 79.838, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist"], avgWaitMin: 61 },
  { name: "Kauvery Hospital, Salem", lat: 11.656, lon: 78.16, departments: ["Cardiologist", "Neurologist", "General Physician", "Orthopedician", "Gynecologist", "Oncologist"], avgWaitMin: 50 },
  { name: "Kauvery Medical Centre, Hosur", lat: 12.7425, lon: 77.829, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist"], avgWaitMin: 33 },
  { name: "Kauvery Cancer Institute, Trichy", lat: 10.795, lon: 78.702, departments: ["Oncologist", "General Physician", "Neurologist"], avgWaitMin: 32 },
  { name: "Apollo First Med Hospitals, Kilpauk", lat: 13.0832, lon: 80.2421, departments: ["General Physician", "Cardiologist", "Neurologist", "Gynecologist", "Orthopedician"], avgWaitMin: 42 },
  { name: "Narayana Hospital, Salem", lat: 11.661, lon: 78.155, departments: ["General Physician", "Cardiologist", "Orthopedician", "Gynecologist"], avgWaitMin: 38 },
  { name: "Narayana Health, Coimbatore", lat: 11.012, lon: 77.005, departments: ["Cardiologist", "Neurologist", "Orthopedician", "General Physician", "Oncologist"], avgWaitMin: 51 },
  { name: "Lakshmi Hospital, Palakkad Road, Coimbatore", lat: 11.0301, lon: 76.9968, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 42 },
  { name: "Aravind Eye Hospital, Coimbatore", lat: 11.0023, lon: 76.975, departments: ["General Physician", "Dermatologist", "Neurologist"], avgWaitMin: 30 },
  { name: "Aravind Eye Hospital, Tirunelveli", lat: 8.72, lon: 77.754, departments: ["General Physician", "Dermatologist", "Neurologist"], avgWaitMin: 32 },
  { name: "Aravind Eye Hospital, Trichy", lat: 10.778, lon: 78.687, departments: ["General Physician", "Dermatologist", "Neurologist"], avgWaitMin: 28 },
  { name: "Apollo Specialty Cancer Hospital, Chennai", lat: 13.0614, lon: 80.2617, departments: ["Oncologist", "General Physician", "Neurologist", "Cardiologist"], avgWaitMin: 52 },
  { name: "Cancer Institute (WIA), Adyar", lat: 12.9941, lon: 80.245, departments: ["Oncologist", "General Physician", "Gynecologist"], avgWaitMin: 45 },
  { name: "RMD Medical Specialities Hospital, Tiruvallur", lat: 13.1442, lon: 79.9088, departments: ["General Physician", "Gynecologist", "Orthopedician", "Cardiologist"], avgWaitMin: 36 },
  { name: "Karpaga Vinayaga Medical College, Maduranthakam", lat: 12.4942, lon: 79.898, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist", "Neurologist"], avgWaitMin: 56 },
  { name: "Sri Balaji Medical College, Chromepet", lat: 12.9516, lon: 80.1448, departments: ["General Physician", "Cardiologist", "Neurologist", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 59 },
  { name: "Meenakshi Ammal Dental College, Alapakkam", lat: 13.0419, lon: 80.1753, departments: ["General Physician", "Pediatrician"], avgWaitMin: 40 },
  { name: "Aarupadai Veedu Medical College, Puducherry", lat: 11.9491, lon: 79.798, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician", "Cardiologist"], avgWaitMin: 39 },
  { name: "Indira Gandhi Medical College, Puducherry", lat: 11.9388, lon: 79.838, departments: ["General Physician", "Gynecologist", "Pediatrician", "Cardiologist", "Neurologist"], avgWaitMin: 71 },
  { name: "G.H. Road Government Hospital, Vallam", lat: 10.7635, lon: 79.14, departments: ["General Physician", "Gynecologist", "Pediatrician", "Orthopedician"], avgWaitMin: 79 }
];
